site_name: Technical Advisory Council
repo_name: openwallet-foundation/tac
repo_url: https://github.com/openwallet-foundation/tac
edit_uri: edit/main/docs
copyright: "Copyright &copy; OpenWallet Foundation<br/>License: CC BY 4.0"
theme:
  name: material
  logo: assets/project-logo.png
  favicon: assets/project-icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - content.code.copy
  - content.action.view
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openwallet-foundation
    - icon: fontawesome/solid/flask-vial
      link: https://github.com/openwallet-foundation-labs
      name: Labs (GitHub)
    - icon: fontawesome/brands/discord
      link: https://discord.gg/openwalletfoundation
      name: Discord
    - icon: fontawesome/solid/envelope
      link: https://lists.openwallet.foundation
    - icon: fontawesome/solid/calendar-days
      link: https://zoom-lfx.platform.linuxfoundation.org/meetings/openwalletfoundation
      name: Community Calendar
    - icon: material/presentation
      link: https://drive.google.com/drive/folders/1TW9Och54uAjuKDeYQZ-DUIuNzpDLaLUT?usp=drive_link
      name: Community Presentations (Google Drive)
    - icon: fontawesome/solid/globe
      link: https://openwallet.foundation
nav:
  - Home: index.md
  - Governing Documents:
    - governance/index.md
    - Foundation Governance:
      - Charter: governance/charter.md
      - Antitrust Policy: governance/antitrust.md
      - Code of Conduct: governance/code-of-conduct.md
    - TAC Governance:
      - Roles and Responsibilities: governance/roles-and-responsibilities.md
      - Alternate Policy: governance/alternate-policy.md
      - Elections: governance/elections.md
      - Project Lifecycle: governance/project-lifecycle.md
      - Special Interest Groups: governance/special-interest-group-process.md
      - Task Forces: governance/task-force-process.md
      - Composition: governance/tac.md
    - Project Requirements:
      - Annual Review Process: governance/project-annual-review-process.md
      - Common Repository Structure: governance/common-repository-structure.md
      - MAINTAINERS.md Contents: governance/maintainers-file-content.md
      - Maintainer Inactivity: governance/maintainer-inactivity.md
      - Security Policy: governance/security.md
      - Release Taxonomy: governance/release-taxonomy.md
      - Inactive Repositories: governance/archiving-inactive-repositories.md
    - Project Resources:
      - Paid Tooling Policy: governance/paid-tooling-policy.md
      - Project and Lab Services: governance/project-and-lab-services.md
      - Content Plan: governance/content-plan.md
  - Meetings:
    - meetings/index.md
    - 2024:
      - 2024-09-04: meetings/2024/2024-09-04.md
      - 2024-08-21: meetings/2024/2024-08-21.md
      - 2024-08-07: meetings/2024/2024-08-07.md
      - 2024-07-24: meetings/2024/2024-07-24.md
      - 2024-07-10: meetings/2024/2024-07-10.md
      - 2024-06-26: meetings/2024/2024-06-26.md
      - 2024-06-12: meetings/2024/2024-06-12.md
      - 2024-05-29: meetings/2024/2024-05-29.md
      - 2024-05-15: meetings/2024/2024-05-15.md
      - 2024-05-01: meetings/2024/2024-05-01.md
      - 2024-04-17: meetings/2024/2024-04-17.md
      - 2024-04-03: meetings/2024/2024-04-03.md
      - 2024-03-20: meetings/2024/2024-03-20.md
      - 2024-03-06: meetings/2024/2024-03-06.md
      - 2024-02-21: meetings/2024/2024-02-21.md
      - 2024-02-07: meetings/2024/2024-02-07.md
      - 2024-01-24: meetings/2024/2024-01-24.md
      - 2024-01-10: meetings/2024/2024-01-10.md
    - 2023:
      - 2023-12-13: meetings/2023/2023-12-13.md
      - 2023-11-29: meetings/2023/2023-11-29.md
      - 2023-11-15: meetings/2023/2023-11-15.md
      - 2023-11-01: meetings/2023/2023-11-01.md
      - 2023-10-18: meetings/2023/2023-10-18.md
      - 2023-10-04: meetings/2023/2023-10-04.md
      - 2023-09-20: meetings/2023/2023-09-20.md
      - 2023-09-06: meetings/2023/2023-09-06.md
      - 2023-08-23: meetings/2023/2023-08-23.md
      - 2023-08-09: meetings/2023/2023-08-09.md
      - 2023-07-26: meetings/2023/2023-07-26.md
      - 2023-07-12: meetings/2023/2023-07-12.md
      - 2023-06-28: meetings/2023/2023-06-28.md
      - 2023-06-14: meetings/2023/2023-06-14.md
      - 2023-05-31: meetings/2023/2023-05-31.md
      - 2023-05-17: meetings/2023/2023-05-17.md
      - 2023-05-03: meetings/2023/2023-05-03.md
      - 2023-04-19: meetings/2023/2023-04-19.md
      - 2023-04-05: meetings/2023/2023-04-05.md
      - 2023-03-22: meetings/2023/2023-03-22.md
      - 2023-03-08: meetings/2023/2023-03-08.md
  - Projects:
    - projects/index.md
    - Growth:
      - Bifold: projects/bifold.md
      - Credo: projects/credo-ts.md
    - Labs:
      - Credhub: projects/credhub.md
      - EUDI Wallet Kit React Native: projects/eudi-wallet-kit-react-native.md
      - Farmworker Wallet OS: projects/fwos.md
      - Identity Credential: projects/identity-credential.md
      - MDL JavaScript: projects/mdl-js.md
      - Multiformat VC for iOS: projects/multiformat-vc-ios.md
      - SD-JWT .NET: projects/sd-jwt-dotnet.md
      - SD-JWT JavaScript: projects/sd-jwt-js.md
      - SD-JWT Kotlin: projects/sd-jwt-kotlin.md
      - SD-JWT Python: projects/sd-jwt-python.md
      - SD-JWT Rust: projects/sd-jwt-rust.md
      - Trust Spanning Protocol: projects/tsp.md
      - Tuvali: projects/tuvali.md
      - VC-API: projects/vc-api.md
      - Wallet Framework .NET: projects/wallet-framework-dotnet.md
    - Annual Reviews:
      - 2024:
        - projects/reviews/2024/index.md
      - 2025:
        - projects/reviews/2025/index.md
    - Dashboards: projects/dashboards/index.md
  - Special Interest Groups:
    - SIGs/index.md
    - Architecture: SIGs/architecture.md
    - Credential Format Comparison: SIGs/credential-format-comparison.md
    - Digital Wallet and Agent Overviews: SIGs/digital-wallet-and-agent-overviews.md
    - Safe Wallet: SIGs/safe-wallet.md
    - Quarterly Updates:
      - 2024:
        - SIGs/updates/2024/index.md
  - Task Forces:
    - task-forces/index.md
    - Archived:
        - OID4VC Due Diligence: task-forces/OID4VC-due-diligence.md
not_in_nav: |
  governance/security-template.md
  meetings/YYYY-mm-dd.md
  projects/reviews/0000-template-annual.md
  projects/dashboards/owf.md
  projects/dashboards/labs.md
  projects/reviews/2024/2024-sd-jwt-python-annual.md
